version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123Rambo # Cambia esto por tu contraseña de root
      MYSQL_DATABASE: prueba2 # Nombre de la base de datos
    ports:
      - "3306:3306" # Mapeo de puerto local al puerto del contenedor (opcional)
    volumes:
      - mysql_data:/var/lib/mysql # Persistencia de datos

volumes:
  mysql_data: